### ISSUE TITLE
Add kotlin/js and kotlin/wasm sqlite driver

### ISSUE THREAD

**Issue by vdshb** [smyrgeorge/sqlx4k#1] opened 2024-08-26 07:35 UTC
It probably shouldn't be addressed here, but I'll take a shot. 

There were two missing sql-drivers in kotlin ecosystem I'd like to find: native-postgresql (you closed this gap, huge thanks) and wasm/js-sqlite.

I wonder if it is suitable to add kotlin/js and/or kotlin/wasm sqlite driver as well based on https://sqlite.org/wasm/doc/trunk/index.md to this library as well?

**Comment by smyrgeorge** [comment] 2024-08-26 15:45
I could try to compile to wasm.
I'll let you know.

**Comment by smyrgeorge** [comment] 2024-08-26 16:36
It's not trivial to compile to wasm.
The current setup is not going to work as is for wasm.
The problem is that the underlying driver `sqlx` does not compile to wasm (as I saw).

Perhaps the solution could be to compile separately `sqlite` to wasm (from the official guide) and then somehow import the `.wasm` file into kotlin.

I think, at least for now, I'm not planning to support wasm target.
It's kind of a different project. Of course if you have any extra ideas feel free to tell me 😄 

I think we should close this issue for now.

Thanks

**Closed** 2024-08-26 20:36 UTC
